name: Node.js CI

on:
  push:
    branches:
      - develop

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Npm Install
        run: npm install

      - name: Fetch Resource
        run: npm run fetch:all

      - name: Build Dist
        env:
          GA_ID: ${{ secrets.GA_ID }}
          NODE_ENV: production
          NODE_OPTIONS: --max_old_space_size=4096
        run: npm run dist

  create-release:
    if: ${{ github.ref == 'refs/tags/*' }}
    needs: build-windows
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: false
